---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install strawberryperl
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - perl -v
    - if not exist C:\Perl5 mkdir C:\Perl5
    - SET PATH=C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/Perl5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
    - SET PERL_MB_OPT=--install_base C:/Perl5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
    - cpanm -n .

build: off

test_script:
    - perl Makefile.PL
    - gmake
    - gmake test
    - gmake disttest

cache:
    - C:\Perl5

shallow_clone: true

